[package]
name = "round-cat"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.37.3"
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
winit = "0.28.7"
egui-winit-ash-integration = { git = "https://github.com/YouSafe/egui-winit-ash-integration", branch = "main" }
gpu-allocator = "0.23.0"
egui = "0.23.0"
