
[workspace]
resolver = "2"
members = [ 
  "asset_common", 
  "asset_client", 
  "asset_server",
  "demo"
]

[profile.dev.package.gltf]
opt-level = 2


[profile.dev.package.bincode]
opt-level = 2

[profile.dev.package.serde]
opt-level = 2
