[package]
name = "asset_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomicwrites = "0.4.2"
env_logger = "0.10.1"
ipc-channel = "0.18.0"
tokio = "1.34.0"
